language: node_js
node_js: "6"

env:
  global:
    - REPO_SLUG=tomusdrw/rust-assert-diff
    - secure: "DMNQHXIFOe7AexBN1DDi2y9IvGxDQ4sL0gtXUlGq1a2/luXlD7ofJpfnwR1LqwAmICZxqp2FIp3juaArcy+U7wCmI2NSJzq2SqWnhMFyth/Hqa/24M+UaTBvgJaImYJeT9aExNYBvLvmI+ITZXdTORI6zmv5SCiYucvo+Up31AqBQr8uxJyzmrounM5U4a2g1PfSThS0fC0QLshDEKxCSQXBMwVf8WbfB/RxdlguadCqRCe2fN5LY1mCkyhyyiGP2jCBGcDHe0lKIbku/2Zei/+7AycId//D9kofOHHuND+iUsRMzIqyidgKZ+4QeADyWhnwOlqxo/LK86ItZUUCjjw90QygSb3AXfcvAkjyBwTrF6ol70D++3TKFPhBiCTSYecOUavYtH2q9mReSQPDN4p7EXW5F/6zv/GzNElXjCmp1hmNnUis/YUiWj+dyo1uMLiWQW/68YPQ7Spt262MKrLR8iATXvwqLgT2fdhiIuY2pAbXTodkybrwmVc20Zfkuf1iuDiDjZxyC/rNx1lnRFL0LyVZVVO1K/PIJ/tCLGf+DAgqNcVzTQvc5MjQEtLWyvQ3DrILr61tzmEwrUsaBAtIQ7ynuE5ybZ9+NXzJ9cfoTIoWtKQZDdpUMPhHQvO3ozX74O50TybqDqgYS9H+KVPa1n5z0tCCFbu0MiNfzZM="

script:
  - npm run build

after_success:
  - ./scripts/deploy-to-gh-pages.sh
